[package]
name = "test_vectors"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
hex = "0.4"
lazy_static = "1.4.0"
